name: new-festim-environment

channels:
- defaults
- conda-forge

dependencies:
- festim
- gmsh
- python-gmsh
- pyvista
- numpy
- mpi4py
- MPI


# - ipykernel   # if you run notebooks you'll probably need this